### PR TITLE
Add support for Ubuntu 22.04

### LINKED ISSUE #22: [Feature]: Add support for Ubuntu 22.04
### Description

Rancher 2.6.9 will introduce support fro Ubuntu 22.04.

Would it be possible to update the UI driver to add this to the list of OSes?

### PR DESCRIPTION
**Pull request by nwmac**
Fixes #22

Adds support for Ubuntu 22.04.

Added release 0.5.0

Tested in Rancher 2.6.

### CODE REVIEW

**Comment by LBGarber** [comment]
Thanks for the contribution!

I'll test provisioning `Ubuntu 22.04` clusters using this change and get back to you.

**Comment by LBGarber** [comment]
@nwmac

I tested this against my local Rancher instance (`rancher/rancher:v2.6-head`) and all seems good from a UI perspective. There were some provisioning errors with Ubuntu 22.04, but it looks like this is already a [known issue](https://github.com/rancher/rancher/issues/38362) with the Docker install script. Modifying my Docker install URL to use `install-docker-dev` as mentioned in the thread seems to function as expected.

**Review by LBGarber — APPROVED** [review]

**Comment by nwmac** [comment]
Thanks @LBGarber - Rancher 2.6.9 will add support for Ubuntu 22.04, so the script workaround will no longer be needed.

**Review by jriddle-linode — APPROVED** [review]
Looks good thank you for your help!

**Comment by LBGarber** [comment]
@nwmac This PR has been merged and the new version should now be available at `https://linode.github.io/rancher-ui-driver-linode/releases/v0.5.0/...`

**Pull request merged**
